CREATE DATABASE `AUTOMAP` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `SERVICIOS` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR',
  `DESCRIPCION` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'NOMBRE DEL SERVICIO',
  `PRECIO` int unsigned NOT NULL COMMENT 'PRECIO DEL SERVICIO',
  `MCA_INHABILITADO` enum('S','N') DEFAULT 'N' COMMENT 'MARCA DE INHABILITADO',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `VENTAS` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR',
  `CLIENTE` varchar(100) NOT NULL COMMENT 'NOMBRE DEL CLIENTE',
  `DESCRIPCION_VENTA` varchar(1000) NOT NULL COMMENT 'DESCRIPCION DE LOS SERVICIOS VENDIDOS',
  `TOTAL_VENTA` int unsigned NOT NULL COMMENT 'MONTO TOTAL DE LA VENTA',
  `FECHA_REGISTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DE CREACION DEL REGISTRO',
  `MCA_INHABILITADO` enum('S','N') NOT NULL DEFAULT 'N' COMMENT 'MARCA DE INHABILITADO',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DETALLE_VENTAS` (
  `ID` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR',
  `ID_FACTURA` int unsigned NOT NULL COMMENT 'IDENTIFICADOR DE LA VENTA',
  `ID_SERVICIO` int unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `DETALLE_SERVICIOS_FK` (`ID_SERVICIO`),
  KEY `DETALLE_VENTAS_FK` (`ID_FACTURA`),
  CONSTRAINT `DETALLE_SERVICIOS_FK` FOREIGN KEY (`ID_SERVICIO`) REFERENCES `SERVICIOS` (`ID`),
  CONSTRAINT `DETALLE_VENTAS_FK` FOREIGN KEY (`ID_FACTURA`) REFERENCES `VENTAS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO AUTOMAP.SERVICIOS (DESCRIPCION,PRECIO,MCA_INHABILITADO) VALUES
	 ('APLICACIÓN DE JABÓN, CERA ESPUMA, ENCERADO, PULIDO Y DESCONTAMINACIÓN DE CARROCERÍA',230000,'N'),
	 ('PORCELÁNICA DE CARROCERÍA, CRISTALIZADO DE CARROCERÍA',450000,'N'),
	 ('LAVADO LLANTAS, CEPILLO LAVA-RUEDAS MULTI-DISK Y CEPILLO LAVA-RUEDAS CON OCHO CEPILLOS',123000,'N'),
	 ('LAVADO A MANO',50000,'N'),
	 ('LAVADO DE MOTOR, LAVADO DE VESTIDURAS DE TELA O PIEL, TEFLÓN EN VESTIDURAS',356000,'N'),
	 ('SECADORA DE CARROS INTEGRADA EN EL EQUIPO',8900,'N'),
	 ('SERVICIO A DOMICILIO',100000,'N');
